name: 'Baidu Tieba Auto Sign'

on:
  push:
    branches:
      - master
  schedule:
    - cron: '5 22 * * *'

jobs:
  tieba_sign:
    runs-on: Ubuntu-20.04
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Set python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'
      - name: 'Install dependencies'
        run: python -m pip install --upgrade requests
      - name: 'Start Sign'
        env:
          BDUSS: ${{ secrets.BDUSS }}
        run: |
           random_time=$(($RANDOM % 10))
           echo "等待 ${random_time} 分钟后开始签到"
           for((i=1;i<=${random_time};i++));  
           do
           echo "倒计时:剩余 $[${random_time}-$i] 分钟"
           sleep 1m
           done
           python main.py
